name: Docker Build and Push
on:
  workflow_run:
    workflows: ["Execute Tests"]
    branches: [ master ]
    types: 
      - completed
  push:
    branches: [ master, CI_pipeline ]
  pull_request:
    branches: [ master ]
jobs:
  Docker_build_and_push:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: login to DockerHub
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run:
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/house-pricing-image
      - name: Deploy Docker Image
        run: |
          docker push $DOCKER_USERNAME/house-pricing-image